### ISSUE TITLE
メディアコンバーターに接続したエコキュートが検出されない

### ISSUE THREAD

**Issue by nana4rider** [banban525/echonetlite2mqtt#1]
はじめまして。お世話になります。
メディアコンバーター([CF-TC7B](https://twitter.com/chobby_game/status/1566221996504928258))とHEMSアダプター([CF-TA9C](https://www2.panasonic.biz/scvb/a2A/opnItemDetail?item_no=CF-TA9C&b_cd=501&hinban_kbn=1&s_hinban_key=CF-TA9C&itmcmp_link_flg=0&itmcmp_add_flg=0&vcata_flg=1&use_obligation=&item_cd=CF-TA9C&catalog_view_flg=1&contents_view_flg=1&close_flg=1&simple_search_flg=))を接続し、ECHONETLite2MQTTで検出を試みましたができませんでした。
原因を調査しましたのでご報告と、改善要望を出させて頂きます。

### `autoGetDelay`が短いと、メディアコンバーターの処理が追いつかずプロパティの取得が完了しない
メディアコンバーター側のスペックの問題だと思いますが、`EL.initialize`の`autoGetDelay`が設定値の100ミリですと検出が完了しません。
10回ほど試してみましたが、500ミリ秒では大丈夫のようでした。

### `autoGetDelay`を変更するオプションの追加

固定で100ミリ秒になっていますが、起動引数で変更できるようにして頂きたいです。

ご検討のほどよろしくお願いいたします。

**Comment by banban525** [comment]
要望ありがとうございます。
問題は理解しました。
早めに対応しようと思います。
ただ、autoGetDelayは長くすると起動までに時間がかかるので悩ましいところです。

**Comment by nana4rider** [comment]
早速の回答ありがとうございます。
banban525さんのTwitterを見つけたのでそちらにも連絡させて頂いたのですが、自分でコードを修正して運用しているので急ぎではありませんm(_ _)m

> ただ、autoGetDelayは長くすると起動までに時間がかかるので悩ましいところです。

そうなんですよね。我が家のエコキュートはプロパティが34項目あるのでデバイスの登録までに結構時間がかかってしまいます。
値の受信を確認したら次の値を取りに行くような作りができれば根本解決できそうですが、echonet-lite.jsがそのような作りになっていなさそうなので実装が大変そうです…。

**Comment by banban525** [comment]
> 値の受信を確認したら次の値を取りに行くような作りができれば根本解決できそうですが、echonet-lite.jsがそのような作りになっていなさそうなので実装が大変そうです…。

なるほど、それは良さそうですね。
echonet-lite.jsのautoGetProperties機能をOFFにして自前実装すれば実現できそうです。
ただ、ちょっと大変そうですね。
また、私のECHONET Lite機器の応答はどれも早いので、根本解決の優先度は低くなりそうです。

他、そちらで実験されているようなので大丈夫だと思いますが、
エコキュートは、ちゃんと対応していないので一部のプロパティは取れないかもしれません。
これに関しては、ECHONET Liteのパーサーを刷新している最中ですのでそちらで解決する予定です。

**Comment by nana4rider** [comment]
> エコキュートは、ちゃんと対応していないので一部のプロパティは取れないかもしれません。
> これに関しては、ECHONET Liteのパーサーを刷新している最中ですのでそちらで解決する予定です。

ありがとうございます。
ひとまず自身の使いたいプロパティは全て利用できたので大丈夫そうです。

[こちら](https://echonet.jp/web_api/)のjsonも確認しましたが、v1.4から全部入りのファイルが入っていないようですね。
仕様変更が大変かと思いますが、頑張ってください😂

**Comment by banban525** [comment]
コミットコメントとの紐づけを忘れていましたが、このコミットで対応しました。
63e4a64626805f8f13100a331bb78a72e45d90a1

また、バージョン番号で管理するようにし、v1.1.0で、この機能に対応しました。

本件はCloseさせていただきます。
