### ISSUE TITLE
Publishing commands to topics using aliases doesn’t appear to work

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#10]
I’m using an alias file to give proper names to my devices. While echonetlite2mqtt appears to publish to the get topics using aliases fine, it doesn’t appear to be observing the set topics for commands using aliases. 

If I publish a command to the original device id, echonetlite2mqtt appears to see the command and respond properly.

**Comment by banban525** [comment]
@aftertommy 

Thank you for your report.
I reproduced the problem.

This is a bug of ECHONETLite2MQTT.
I will fix this soon.

**Comment by banban525** [comment]
@aftertommy 

I fixed this issue in v2.0.2.
Please upgrade and check the fix.

**Comment by aftertommy** [comment]
I just gave it a shot. It appears to be working! Thank you!
