### ISSUE TITLE
Home Assistant MQTT HVAC no longer using `power_` topics

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#11]
I've been setting up my echonetlite air conditioners using echonetlite2mqtt and Home Assistant, and it looks like Home Assistant has stopped supporting the `power_` state and command topics:

https://github.com/home-assistant/core/issues/85187

Instead, it appears that they're using the `mode_command_topic` to determine `off` vs. cooling/heating/etc.

 The echonetlite2mqtt [demos](https://github.com/banban525/echonetlite2mqtt/blob/master/demo/demo.md) set an `off` entry in the `mode_command_topic`, but I don't think that actually will turn the AC off. Instead this was handled via the `power_command_topic`, but that's no longer supported by Home Assistant.

I understand that echonetlite2mqtt is intending to be a 1:1 map between echonetlite and MQTT topics, but maybe we should combine the `operationStatus` and `operationMode` fields into a single MQTT topic? If you wish to maintain backwards compatibility (and maintain the 1:1 mapping), maybe it could be a new topic like:

`echonetlite2mqtt/elapi/v2/devices/dining_ac/properties/virtualOperationMode/set`

"virtual" meaning "this isn't a real echonetLite property, but it maps to them."

Alternatively, clients who use Home Assistant probably need to write their own automations / scripts that monitor a separate set of MQTT topics, then call through to the echonetlite2mqtt topics to bridge.

**Comment by banban525** [comment]
@aftertommy 

Added auto-retry feature in v2.1.0.

This feature may solve your problem.

However, manual retry feature are deferred.
I plan to create a new page "system" or "maintenance" and add manual retry feature to that page.
I'll solve #11 first, because creating a new page takes time.

**Comment by banban525** [comment]
I have resolved this issue in v2.2.0.
Also updated [the examples page](https://github.com/banban525/echonetlite2mqtt/blob/master/demo/demo.md) to remove 'power_command_topic'.

However, double quotes are correct in the payload, so be careful.

Incorrect: `{ 'operationStatus':'true', 'operationMode':'cooling'}`
Correct: `{ "operationStatus":"true", "operationMode":"cooling"}`

**Comment by aftertommy** [comment]
looks to be working. thank you!
