### ISSUE TITLE
operationMode and operationStatus not always retrieved at device discovery?

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#18]
My instance just discovered my living room air conditioner, and while it successfully grabbed a number of properties from the device, it appears to have _not_ received the `operationMode` and `operationStatus` from the device at discovery. I can request the status via the REST API, but this doesn't appear to propagate back through to MQTT.

The end result is that my home assistant air conditioner controls remain in the "off" state even though the air conditioner is running, and echonetlite2mqtt is able to manually fetch the status.

It seems like two issues:

1. making a manual request via REST doesn't end up updating MQTT
2. not all properties are successfully fetched at device discovery

I have the property interval set to `400`, as I wanted to be sure that I'm not flooding devices with requests. Is there a chance this could be resolved by updating to the latest echonetlite node library? 
[echonetlite2mqtt_logs_internalsStatus.zip](https://github.com/banban525/echonetlite2mqtt/files/12164983/echonetlite2mqtt_logs_internalsStatus.zip)

**Comment by banban525** [comment]
@aftertommy 

My guess is that the property was not acquired due to the slow response from the air conditioner.

You should use echonetIntervalToGetProperties.

To fix this problem I have to rebuild the communication process.
But I haven't implemented it yet.

The latest source code has updated the ECHONET Lite library, so the problem may be fixed.
But I still have a bug, so I can't release it.

**Comment by aftertommy** [comment]
Man i wish you had a paypal or something so i give show you my thanks.

**Comment by banban525** [comment]
I am happy that this product is helping you.
But solving the underlying problem takes time.

I plan to implement #12, which still has bugs, first.

**Comment by aftertommy** [comment]
I believe this is working with the latest update.
