### ISSUE TITLE
MQTTクライアントが起動しない

### ISSUE THREAD

**Issue by nana4rider** [banban525/echonetlite2mqtt#2]
お世話になります。
MQTTクライアントが起動しない不具合がありましたので報告致します。

https://github.com/banban525/echonetlite2mqtt/commit/d94de4ff1cffae7ae8a76c0c04a1dbb0cb1ef77b#diff-786114c6ebf98e577ec30dac884800bb7c9ce800b5323710ed03b916e1d33b68R302

`MqttBroker`に値が設定されていると、起動しない分岐になってしまっています。

**Comment by banban525** [comment]
報告ありがとうございます。
ご指摘の通りで、実装ミスですね。
すぐ修正します。

**Comment by nana4rider** [comment]
対応ありがとうございます！
