### ISSUE TITLE
エアコンの風量設定を取得、設定できない

### ISSUE THREAD

**Issue by nana4rider** [banban525/echonetlite2mqtt#3]
お世話になります。
表題の通り、エアコンの風量設定が正しく取得、設定できないようです。

## 値の設定
ざっくり調査したのですが、[こちら](https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_H/Appendix_H.pdf)の仕様書を見る限り、風量は自動が0x41、手動が0x31～0x38のようですが、echonetlite2mqttでは数値の値をそのまま(0x01～0x08)解釈してしまっていることが原因かなと思います。
試しに[このあたり](https://github.com/banban525/echonetlite2mqtt/blob/master/server/echoNetLiteParser.ts#L204)で値を'32'を設定してみたら動作しました。

## 値の取得
風量がAuto以外の際にプロパティ値がundefinedになります。
恐らく前述した問題と同じだと思います。

お手数をおかけしますが、よろしくお願いいたします。

**Comment by nana4rider** [comment]
homeAirConditionerConverterに下記内容を追加で動作しました。

```typescript
  airFlowLevel: {
    toEchoNetLiteData : (schema:DevicePropertySchema, rootProperty:Property,data:number|"auto", currentData:string): string | undefined=>{
      return EL.bytesToString([data === 'auto' ? 0x41 : 0x30 + data]);
    },
    toValue : (echoNetData:EchoNetParseData):number|"auto"|undefined =>{
      const value = EL.toHexArray(echoNetData.data)[0];
      if (value === 0x41) {
        return 'auto';
      } else if (value >= 0x31 && value <= 0x38) {
        return value - 0x30;
      } else {
        return undefined;
      }
    }
  },
```

**Comment by banban525** [comment]
問題を理解しました。
ECHONET Liteの仕様書によると、airFlowLevelは0x41が自動、0x31～0x38が手動で、風量1～8に対応しています。

それに対して、本アプリケーションが根拠にしている
ECHONET Lite Web API ガイドラインでは以下のように1～8の数値として記載されていないため起こっているようです。

```
    "airFlowLevel": {
      "epc": "0xA0",
      "descriptions": {
        "ja": "風量設定",
        "en": "Air flow rate setting"
      },
      "writable": true,
      "observable": true,
      "schema": {
        "oneOf": [
          {
            "type": "number",
            "minimum": 1,
            "maximum": 8
          },
          {
```

0x31 の情報がどこにもないので、自動化は無理で、
ご提案通り、独自にメソッドを追加するしかなさそうです。

ただ、他にも同様の問題がありそうです。
全部は対応できないので、一旦このairFlowLevelだけ対応します。

**Comment by banban525** [comment]
あ、コメントが遅くなり申し訳ありませんでした。

(先のコメントに付けたはずが、抜けていました)

**Comment by banban525** [comment]
ほぼご提案の方法のまま、更新しました。
v1.1.1としてdockerにもpush済みです。
