### ISSUE TITLE
2つ目以降のデバイスクラスが表示されません。

### ISSUE THREAD

**Issue by kscutepoison** [banban525/echonetlite2mqtt#32]
HomeAssistantと連携して便利に使わせていただいております。
太陽光発電と蓄電池の情報を取得したいのですが、echonetlite2mqttで認識されるデバイスが蓄電池（027d）のみで他のデバイスクラスが認識されないです。
ログ内のIP（10.0.1.133）が該当のデバイスです。
[detail.log](https://github.com/user-attachments/files/16384187/detail.log)

この製品（[https://echonet.jp/introduce/gz-000896/](https://echonet.jp/introduce/gz-000896/)）は、1つの製品に3つのデバイスクラスが含まれているのですが、このようなものには対応はされているのでしょうか？
もし対応されていないようでしたら、対応していただけると大変助かります。

なお、02a5のクラスは未定義であったため、`MRA_custom/0x02A5.json`に追加してあります。

```
"selfNodeClassListS": {
    "numberOfClasses": 3,
    "classList": [
      "027d",
      "0279",
      "02a5"
    ]
  }
```

**Comment by banban525** [comment]
返信が遅くなり申し訳ありません。
ログを確認しました。
この機器は、3つのクラスを持っているようですね。

* 0x0279:住宅用太陽光発電
* 0x027d:蓄電池
* 0x02a5:マルチ入力PCS

複数デバイスクラスを持つ機器に関しては、こちらでは問題なく動作しているので、これが原因ではありません。
また、少なくとも、 「0x0279:住宅用太陽光発電」 はクラスの定義が実装済みなので認識するはずでした。

何か別の問題と思われます。

ちょっとコード見ながら原因を考えてみます。

**Comment by banban525** [comment]
@kscutepoison 

たぶん原因がわかりました。

EchonetLite2MQTTは、プロパティ0x83 (識別番号)を各インスタンスのIDにしているのですが、
これが共通であるために、蓄電池しか認識しないという挙動になっているようです。

```
{"level":"warn","message":"ERROR: unknown property. propertyNo === f0 in id: fe00006c424d442d313039343833574455, ip:10.0.1.133, eoj:027901","timestamp":"2024-07-25T14:09:53.220Z"}

{"level":"warn","message":"ERROR: unknown property. propertyNo === f6 in id: fe00006c424d442d313039343833574455, ip:10.0.1.133, eoj:02a501","timestamp":"2024-07-25T14:09:53.226Z"}

{"level":"info","message":"[ECHONETLite] new device:   fe00006c30303030313930343530364437 nodeProfile 10.0.1.133 0ef001","timestamp":"2024-07-25T14:09:53.227Z"}
{"level":"info","message":"[ECHONETLite] new device:   fe00006c424d442d313039343833574455 storageBattery 10.0.1.133 027d01","timestamp":"2024-07-25T14:09:53.232Z"}
```

上記のログから、3つのインスタンスでIDが同じで、ノードプロファイルのみIDが違うようです。

* 027901(住宅用太陽光発電):  `fe00006c424d442d313039343833574455`
* 027d01(蓄電池):  `fe00006c424d442d313039343833574455`
* 02a501(マルチ入力PCS):  `fe00006c424d442d313039343833574455`
* ノードプロファイル: `fe00006c30303030313930343530364437`

この"識別番号"は、仕様に曖昧さがあるのか、機器によって実装が違うようです。
* ケース1: 機器内のインスタンスごとに"識別番号"が違う
* ケース2: 機器内のすべてのインスタンスで"識別番号"が同じ
* ケース3: 機器内のインスタンスの"識別番号"は同じだが、ノードプロファイルだけが違う

ケース1とケース2の機器を持っていたので、EchonetLite2MQTTでは対応していましたが、
ケース3の、ノードプロファイルのみ"識別番号"が違う、というのは想定していなかったので、
"蓄電池"と"太陽光発電"と"マルチ入力PCS"で同じIDになってしまい、"蓄電池"のみ認識されているようです。

これに対応するにはコード修正が必要なので、1週間ほど待ってください。

なお、ver.3.1.2として修正予定ですが、IDのルールが変わるので、すでに認識している"蓄電池"のIDは変わってしまいます。
たぶん、以下のような感じになるかと。

* 027901(住宅用太陽光発電):  `fe00006c424d442d313039343833574455_027901`
* 027d01(蓄電池):  `fe00006c424d442d313039343833574455_027d01`
* 02a501(マルチ入力PCS):  `fe00006c424d442d313039343833574455_02a501`
* ノードプロファイル: `fe00006c30303030313930343530364437`

IDが変わるとHome Assistantの定義を変えないといけなくなるので、
必要なら、エイリアスオプションで調整してください。

**Comment by kscutepoison** [comment]
@banban525 

原因を特定していただきありがとうございます！
大変助かります。

IDが変わることも承知しました。
修正作業よろしくお願いします。

**Comment by banban525** [comment]
@kscutepoison 

本件修正しました。
試してみてください。

https://github.com/banban525/echonetlite2mqtt/releases/tag/v3.1.2

なお、これでも直らない場合は、
Logページの下部にある「Download Logs and internal statues for debug.」から詳細ログをダウンロードして、
ここに添付してもらえるとさらに詳しく調べることができると思います。

**Comment by kscutepoison** [comment]
@banban525 

早速修正いただきありがとうございます。
無事3つのインスタンス全て認識しました。
大変助かりました！
