### ISSUE TITLE
複数プロパティの同時更新について

### ISSUE THREAD

**Issue by nana4rider** [banban525/echonetlite2mqtt#37]
お世話になります。

複数プロパティを同時更新するAPIやMQTTトピックを実装して頂くことは可能でしょうか。
自宅のエアコンにおいて、「エアコンのON(operationStatus)」と「暖房への変更(operationMode)」を同時に行うために両方のプロパティを同時に送信する方法あり、 #3 を対応して頂いたコミットからforkし独自実装を加えた状態で2年ほど運用しておりました。
可能であれば同じような機能を最新版にも取り込んで頂きたいのですが可能でしょうか。

https://github.com/nana4rider/echonetlite2mqtt/commit/59801aa8351cedb94ec557cd2e96071da026a7f3

また、上記で利用しているechonet-lite.jsの`EL.sendELDATA`メソッドにも不具合があり、こちらは下記のプルリクエストを出しています。

https://github.com/Hiroshi-Sugimura/echonet-lite.js/pull/16

ご検討よろしくお願いいたします🙇‍♂️

**Comment by banban525** [comment]
@nana4rider さん

そちらで使われている ECHONETLite2MQTTは ver.1.1.0がベースのようですね。
複数プロパティの一括更新は、ver.2.2.0で実装しています。 (当時のIssue #11 )

https://github.com/banban525/echonetlite2mqtt/releases/tag/v2.2.0

> You can change multiple properties in one publish.
> For example, by issuing the following Json, "operationStatus" and "operationMode" can be changed at the same time.
> 
> ```
> Topic: echonetlite2mqtt/elapi/v2/devices/fe00-your-device-id-00000000000000/properties/set
> Payload: {"operationStatus":"true","operationMode":"cooling"}
> ```

ただし、内部的には一括送信ではなく、連続してコマンドを送っています。
うちのエアコン(ダイキン AN-22YRS , AN-56ZRP )では動作しているようですが、
まだなら一度試してみてください。

なお、メジャーバージョンをまたぐと仕様変更していますのでその点に注意してください。
一番大きいのはこれです。
> Default MQTT topic name changed from "echonetlite2mqtt/elapi/v1" to "echonetlite2mqtt/elapi/v2".

**Comment by nana4rider** [comment]
@banban525 
ありがとうございます。
最新版で試してみたところ自宅の機器エアコン、エコキュートが無事検出され、上記の複数プロパティ更新もできました。
厳密には起動後すぐにモードを切り替える動きになるので若干挙動が異なりますが、冷暖房の切り替えは基本季節の変わり目だけなので特に問題もなさそうです。

インターフェースも独自実装していたものとほぼ同じで簡単に移行できそうです。
本issueはクローズしますが、気になった点が2つありました。

### プロパティの列挙順について
当たり前ですが、電源OFF時に下記を送信するとモードの変更に失敗します。
```json
{"operationMode":"cooling","operationStatus":"true"}
```
プロパティの列挙順について調べたところ、少なくともfor...inについては順序を保持するソースを見つけられました。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...in
ただ、JSON.parse時に保証されるかどうかはハッキリしませんでした。
基本的には保持されるようなので問題なさそうですが、調べたので一応残しておきます…。

### 戻り値の型について
`echonetlite2mqtt/elapi/v2/devices/{id}/properties`の戻り値ですが、boolean型の戻り値がstringになっています。
数値型の方はnumberだったので少し気になりました。

**Comment by banban525** [comment]
@nana4rider 

> 戻り値の型について

これは、おそらく"operationStatus"なんかが、昔はbooleanだったものが、"true" or "false"になっているということですね。
気が付いていませんでしたが、ver.1.x.x → ver.2.x.x の時にECHONET Lite周りのパーサーを
Web APIベースから、Machine Readable Appendix ベースに変えた副作用と思われます。

ECHONET Machine Readable Appendix (MRA)
https://echonet.jp/spec_mra_rr2/

このMachine Readable Appendixに従っているほうが標準に近いので、ECHONETLite2MQTTからすると仕様変更ですが、このまま行くつもりです。

> プロパティの列挙順について

これは、このIssueの前のコメントを書いている最中に問題あるかもって気付きました。
現状は問題ないとのことですが、将来的にjsonのプロパティ順を壊してしまう可能性があるので、あまりよくないですね。
ECHONET Liteの仕様に従って一括送信に対応したほうがいい気がしています。
ただ、一括送信はおそらくデバイス側の都合で受け付ける数に制限がありそうで、面倒そうではあります。

**Comment by nana4rider** [comment]
もし後方互換性を保ちつつ現在の送信方法で順序を保証したAPIを実装するのであれば、下記のように配列を渡せるようにすればいいと思います。
```json
[
  {"operationMode":"cooling"},
  {"operationStatus":"true"}
]
```
