### ISSUE TITLE
Feature Request: HASS Addon?

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#7]
It would be _fantastic_ if this could be wrapped into an add-on for Home Assistant OS / Supervised. I'm new to HASS development, so I'm not quite sure how to do it, but my understanding is it's mostly a wrapper around `docker run` commands?

echonetlite2mqttをHASSのアドオンにして頂ければ幸いです。こちらではhome assistant yellowの環境でhassosのuiで追加できれば助かります。あまりhassの開発に詳しくないですが、アドオンはdockerのラッパーに近いようですね。

**Comment by banban525** [comment]
@aftertommy 

Thank you for your request.
This request is currently low priority because I'm not using HASS.

**Comment by aftertommy** [comment]
thank you. I will close this issue.
